---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a stack containing an IAM role used to grant
  grant Grand Central access to create CloudFormation stacks
  to enable collection of AWS logging data to send to Splunk

Parameters:
  GrandCentralInstanceProfileARN:
    Type: String
    Description: ARN of the instance profile on which Grand Central runs

Resources:
  SplunkOrgListerCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SplunkOrgListerCrossAccountRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref GrandCentralInstanceProfileARN
          Action:
          - sts:AssumeRole
  SplunkOrgListerCrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SplunkOrgListerIntegrationPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
          - organizations:ListAccounts
          Effect: Allow
          Resource: "*"          
      Roles: [!Ref SplunkOrgListerCrossAccountRole]

Outputs:
  RoleId:
    Description: The logical ID of the IAM role
    Value: !Ref SplunkOrgListerCrossAccountRole
  RoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt [SplunkOrgListerCrossAccountRole, Arn]
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref SplunkOrgListerCrossAccountPolicy