---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a stack containing an IAM role used to grant
  grant Grand Central access to create CloudFormation stacks
  to enable collection of AWS logging data to send to Splunk

Parameters:
  GrandCentralInstanceProfileARN:
    Type: String
    Description: ARN of the instance profile on which Grand Central runs

Resources:
  SplunkDataCollectionCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SplunkDataCollectionCrossAccountRole
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref GrandCentralInstanceProfileARN
          Action:
          - sts:AssumeRole
  SplunkDataCollectionCrossAccountPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SplunkDataCollectionIntegrationPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
            - autoscaling:Describe*
            - cloudformation:*
            - cloudwatch:Describe*
            - cloudwatch:Get*
            - cloudwatch:List*
            - cloudwatch:PutMetricData
            - config:DeliverConfigSnapshot
            - config:DescribeConfigRuleEvaluationStatus
            - config:DescribeConfigRules
            - config:GetComplianceDetailsByConfigRule
            - config:GetComplianceSummaryByConfigRule
            - ec2:DescribeAddresses
            - ec2:DescribeImages
            - ec2:DescribeInstances
            - ec2:DescribeKeyPairs
            - ec2:DescribeNetworkAcls
            - ec2:DescribeRegions
            - ec2:DescribeReservedInstances
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSnapshots
            - ec2:DescribeSubnets
            - ec2:DescribeVolumes
            - ec2:DescribeVpcs
            - events:DescribeRule
            - events:PutEvents
            - events:PutRule
            - events:PutTargets
            - firehose:CreateDeliveryStream
            - firehose:DeleteDeliveryStream
            - firehose:DescribeDeliveryStream
            - iam:AttachRolePolicy
            - iam:CreateRole
            - iam:DeleteRole
            - iam:DeleteRolePolicy
            - iam:DetachRolePolicy
            - iam:GetAccessKeyLastUsed
            - iam:GetRole
            - iam:PassRole
            - iam:PutRolePolicy
            - kinesis:DescribeStream
            - kinesis:Get*
            - kinesis:ListStreams
            - kms:Decrypt
            - lambda:CreateFunction
            - lambda:DeleteFunction
            - lambda:GetFunctionConfiguration
            - lambda:RemovePermission
            - logs:DeleteSubscriptionFilter
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:GetLogEvents
            - logs:PutSubscriptionFilter
            - s3:CreateBucket
            - s3:DeleteBucket
            - s3:GetAccelerateConfiguration
            - s3:GetBucketCORS
            - s3:GetBucketLocation
            - s3:GetBucketLogging
            - s3:GetBucketPolicy
            - s3:GetBucketPolicyStatus
            - s3:GetBucketPublicAccessBlock
            - s3:GetBucketTagging
            - s3:GetLifecycleConfiguration
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:ListAllMyBuckets
            - s3:ListBucket
            - s3:PutBucketVersioning
            - sts:AssumeRole
          Effect: Allow
          Resource: "*"          
      Roles: [!Ref SplunkDataCollectionCrossAccountRole]

Outputs:
  RoleId:
    Description: The logical ID of the IAM role
    Value: !Ref SplunkDataCollectionCrossAccountRole
  RoleArn:
    Description: The ARN of the IAM role
    Value: !GetAtt [SplunkDataCollectionCrossAccountRole, Arn]
  PolicyId:
    Description: The logical ID of the IAM policy
    Value: !Ref SplunkDataCollectionCrossAccountPolicy
